version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=shopdb
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=shopdb
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=your_secret_key
    depends_on:
      - db

volumes:
  postgres_data:
